version: "3.5"

services:
  nginx-rtmp-hls:
#    image: alqutami/rtmp-hls:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1935:1935
      - 8080:8080
